#!/usr/bin/env python

import sys

Import("env")

common_server = [
    "#platform/linuxbsd/display_server_x11.cpp"    
]

if sys.platform == "darwin":
    common_server.append("#platform/osx/crash_handler_osx.mm")
else:
    common_server.append("#platform/linuxbsd/crash_handler_linuxbsd.cpp")

prog = env.add_program("#bin/godot_server", ["godot_server.cpp"] + common_server)
